import subprocess
import sys
import os
import shutil
import datetime


def get_git_version():
    try:
        return subprocess.check_output(
            ["git", "describe", "--tags", "--always", "--dirty"],
            stderr=subprocess.DEVNULL
        ).decode().strip()
    except Exception:
        return "unknown"


def get_git_commit():
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            stderr=subprocess.DEVNULL
        ).decode().strip()
    except Exception:
        return "unknown"


def write_version_file():
    version = get_git_version()
    commit  = get_git_commit()
    build   = datetime.date.today().isoformat()
    with open("version.py", "w") as f:
        f.write("# auto-generated by build.py — do not edit\n")
        f.write(f'__version__ = "{version}"\n')
        f.write(f'__commit__  = "{commit}"\n')
        f.write(f'__build__   = "{build}"\n')
    return version, commit, build


def main():
    print("=" * 60)
    print("Building Recursive Video Player")
    print("=" * 60)

    print("\n[1/6] Writing version info...")
    version, commit, build = write_version_file()
    print(f"  version : {version}")
    print(f"  commit  : {commit}")
    print(f"  date    : {build}")

    print("\n[2/6] Cleaning previous builds...")
    dirs_to_clean = ['build', 'dist', '__pycache__']
    for dir_name in dirs_to_clean:
        if os.path.exists(dir_name):
            shutil.rmtree(dir_name)
            print(f"  Removed: {dir_name}")

    subprocess.run([sys.executable, '-m', 'pip', 'install', 'pyinstaller'], check=True)

    print("\n[5/6] Building with PyInstaller...")
    subprocess.run([sys.executable, '-m', 'PyInstaller', 'video_player.spec', '--clean'], check=True)

    print("\n[6/6] Post-build cleanup...")

    print("\n" + "=" * 60)
    print("Build Complete!")
    print("=" * 60)
    print(f"\n  Version    : {version}")
    print(f"  Commit     : {commit}")
    print(f"  Build date : {build}")
    print(f"\nExecutable location: {os.path.abspath('dist/RecursiveVideoPlayer/RecursiveVideoPlayer.exe')}")
    print("\nNOTE: Before distributing, ensure:")
    print("  1. VLC is installed on target system")
    print("  3. Test all features thoroughly")


if __name__ == '__main__':
    main()